image:
  registry: snagarju
  repository: user
  tag: latest  # will be replaced
  pullPolicy: Always

namespace: qtapp

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
env:
  GIN_MODE: debug
  GIN_ACCESS_LOG: true

service:
  name: user
  serviceType: ClusterIP
  internalPort: 8080
  externalPort: 8080

deps:
  UserURL: user.qtapp.svc.cluster.local:8080
  PaymentURL: payment.qtapp.svc.cluster.local:8080
  OrderURL: order.qtapp.svc.cluster.local:8080
  SqlUser: root
  SqlPassword: password
  SqlHost: mysql.mysql.svc.cluster.local:3306
  SqlDB: signoz
  Collector: signoz-otel-collector.observability.svc.cluster.local:4317
